name: ci-pulse-mailer

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  check-application:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.4

        env:
          DB_PASSWORD: jsow92j29u8whona9
          DB_USERNAME: postgres
          DB_NAME: Pulse_Mailer

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: jsow92j29u8whona9
          DB_NAME: Pulse_Mailer
          SSL_MODE: disable

      - name: Test coverage
        run: go test -v ./... -coverprofile=coverage.out -covermode=atomic
